# Generated by Django 5.0.3 on 2024-05-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_actor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
